version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      # https://github.com/pypa/pipenv/issues/1648
      - run: pip install --user -e git+https://github.com/pypa/pipenv.git#egg=pipenv
      - run: python -m pipenv install --dev
      - run: pwd; ls
      - run: python -m pipenv run python -m pytest --junitxml=.pytest/junit.xml
      - run: mv .pytest $CIRCLE_TEST_REPORTS/pytest
      - run: bash <(curl -s https://codecov.io/bash)
